runtime: python39

instance_class: F1 
entrypoint: python main.py

env_variables:
  GOOGLE_CLOUD_PROJECT: "bot-pib-engine"

automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1
  max_instances: 1
