runtime: python39

instance_class: F1  # Classe de instância gratuita

entrypoint: python main.py

env_variables:
  GOOGLE_CLOUD_PROJECT: "thermal-cathode-330516"

automatic_scaling:
  target_cpu_utilization: 0.5
  min_instances: 1
  max_instances: 1
